### ISSUE TITLE
cloudwatch_log_group encryption rule is misleading or incorrect

### ISSUE THREAD

**Issue by dayer4b** [Checkmarx/kics#5862] opened 2022-09-30 18:08 UTC
As [documented by AWS](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/encrypt-log-data-kms.html),

> Log group data is always encrypted in CloudWatch Logs. By default, CloudWatch Logs uses server-side encryption for the log data at rest. As an alternative, you can use AWS Key Management Service for this encryption. If you do, the encryption is done using an AWS KMS customer managed key. Encryption using AWS KMS is enabled at the log group level, by associating a key with a log group, either when you create the log group or after it exists.

However, **kics** has a rule that necessitates the usage of KMS for encryption.

https://github.com/Checkmarx/kics/blob/cd24fef396d5c9b954cfc7995496f151e86b0683/assets/queries/terraform/aws/cloudwatch_log_group_not_encrypted/metadata.json#L3-L4

I would argue that this may constitute a severity of `"INFO"` if it is necessary at all.

At the very least it is disingenuous to suggest that the cloudwatch log groups are not encrypted if an AWS KMS key is not applied.

**Comment by cxMiguelSilva** [comment] 2022-10-17 15:33
Hi @dayer4b,
I'm glad to inform you that the issue is being addressed in #5943.
Thank you so much for your input!

**Closed** 2022-10-18 08:47 UTC
