### ISSUE TITLE
Latest kics-github-action fails with new v1.6.12 kics release

### ISSUE THREAD

**Issue by brucetieu** [Checkmarx/kics#6234] opened 2023-03-14 19:22 UTC
Our job running the kics-github-action on version 1.6.2 is failing with a `Cannot find module '/app/dist/index.js'` error.

### Expected Behavior

```
> kics-github-action@1.0.0 build
> ncc build src/main.js

ncc: Version 0.31.1
ncc: Compiling file index.js into CJS
727kB  dist/index.js
727kB  [4117ms] - ncc 0.31.1
```

### Actual Behavior

```
> kics-github-action@1.0.0 build
> ncc build src/main.js

ncc: Version 0.31.1
ncc: Compiling file index.js into CJS
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at hashOf (/app/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:37:1855992)
    at ncc (/app/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:37:1860457)
    at runCmd (/app/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:55128)
    at 819 (/app/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:51698)
    at __webpack_require__ (/app/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:59048)
    at /app/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:59260
    at /app/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:59321
    at Object.<anonymous> (/app/node_modules/@vercel/ncc/dist/ncc/cli.js:8:28) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
node:internal/modules/cjs/loader:[107](https://github.com/invitation-homes/terraform-aws-lambda-module/actions/runs/4418907257/jobs/7746642827#step:5:108)8
  throw err;
  ^

Error: Cannot find module '/app/dist/index.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.14.2
```

We believe this is caused by version 1.6.12 of [kics](https://github.com/Checkmarx/kics) being released. Therefore, we rolled back the version of the kics-github-action to use v1.5 (`uses: checkmarx/kics-github-action@v1.5`), and the error went away.

**Comment by Meroje** [comment] 2023-03-15 10:53
this is fixed by https://github.com/Checkmarx/kics-github-action/releases/tag/v1.6.3

**Comment by gabriel-cx** [comment] 2023-03-15 11:07
Hi,

Kindly use the latest version of the KICS github action (v1.6.3).
A fix was merged. The action should now work without a problem.

Please close this issue if the problem is no longer present.

**Comment by gabriel-cx** [comment] 2023-03-15 12:29
Looks like [KICS github action v1.6.3 ](https://github.com/Checkmarx/kics-github-action/releases/tag/v1.6.3) is working fine: this issue is no longer present.
Kindly use that version.

**Closed by gabriel-cx** 2023-03-15 12:29 UTC
Labels: bug, community
