### ISSUE TITLE
panic: interface conversion: interface {} is json.SimpleJSONValue, not string for aws_acm_certificate certificate_body

### ISSUE THREAD

**Issue by arighosh2014** [Checkmarx/kics#5808] opened 2022-09-19 13:22 UTC
### Expected Behavior

KICS should run without any errors

### Actual Behavior

Preparing Scan Assets: Done panic: interface conversion: interface {} is json.SimpleJSONValue, not string

goroutine 71 [running]:
github.com/Checkmarx/kics/pkg/parser/terraform.processElements(0xc001dbd430?, {0xc00068d620, 0x1a})
	/app/pkg/parser/terraform/terraform.go:60 +0x113
github.com/Checkmarx/kics/pkg/parser/terraform.processResources(0x21bab40?, {0xc00068d620, 0x1a})
	/app/pkg/parser/terraform/terraform.go:75 +0x190
github.com/Checkmarx/kics/pkg/parser/terraform.addExtraInfo({0xc000418878?, 0x1, 0x1}, {0xc00068d620, 0x1a})
	/app/pkg/parser/terraform/terraform.go:86 +0xaf
github.com/Checkmarx/kics/pkg/parser/terraform.(*Parser).Parse(0xc000e09d60, {0xc00068d620, 0x1a}, {0xc0018d3800, 0x1549, 0x1800})
	/app/pkg/parser/terraform/terraform.go:126 +0x1ef
github.com/Checkmarx/kics/pkg/parser.(*Parser).Parse(0xc000948210, {0xc00068d620, 0x1a}, {0xc0018d3800, 0x1549, 0x1800})
	/app/pkg/parser/parser.go:128 +0x18d
github.com/Checkmarx/kics/pkg/kics.(*Service).sink(0xc0009d1420, {0x2a1bd20, 0xc000122000}, {0xc00068d620, 0x1a}, {0x242c809, 0x7}, {0x2a00140, 0xc000418088}, {0xc001380000, ...})
	/app/pkg/kics/sink.go:42 +0x1c7
github.com/Checkmarx/kics/pkg/kics.(*Service).PrepareSources.func1({0x2a1bd20, 0xc000122000}, {0xc00068d620, 0x1a}, {0x2a0a990?, 0xc000418088})
	/app/pkg/kics/service.go:70 +0x107
github.com/Checkmarx/kics/pkg/engine/provider.(*FileSystemSourceProvider).walkDir.func1({0xc00068d620, 0x1a}, {0x2a22520, 0xc0019b51e0}, {0x0?, 0x0?})
	/app/pkg/engine/provider/filesystem.go:184 +0x53f
path/filepath.walk({0xc00068d620, 0x1a}, {0x2a22520, 0xc0019b51e0}, 0xc0011e9e18)
	/usr/local/go/src/path/filepath/path.go:433 +0x123
path/filepath.walk({0xc000c18556, 0x5}, {0x2a22520, 0xc0010400d0}, 0xc001dbde18)
	/usr/local/go/src/path/filepath/path.go:457 +0x285
path/filepath.Walk({0xc000c18556, 0x5}, 0xc001046e18)
	/usr/local/go/src/path/filepath/path.go:520 +0x6c
github.com/Checkmarx/kics/pkg/engine/provider.(*FileSystemSourceProvider).walkDir(0xc000c18556?, {0x2a1bd20?, 0xc000122000?}, {0xc000c18556?, 0x10000000000?}, 0x0, 0x18?, 0x7f3204190f18?, 0x20?)
	/app/pkg/engine/provider/filesystem.go:146 +0x91
github.com/Checkmarx/kics/pkg/engine/provider.(*FileSystemSourceProvider).GetSources(0xc000b8cec0, {0x2a1bd20, 0xc000122000}, 0x0?, 0xc000568000, 0x0?)
	/app/pkg/engine/provider/filesystem.go:135 +0x1ce
github.com/Checkmarx/kics/pkg/kics.(*Service).PrepareSources(0xc0009d1420, {0x2a1bd20, 0xc000122000}, {0x242c809, 0x7}, 0x0?, 0x0?)
	/app/pkg/kics/service.go:66 +0x207
created by github.com/Checkmarx/kics/pkg/scanner.PrepareAndScan
	/app/pkg/scanner/scanner.go:24 +0xe7

### Steps to Reproduce the Problem

1.  Put the following block in main.tf file. It is a sample code to just replicate the issue.
```
resource "aws_acm_certificate" "production_graphql_cert" {

  private_key      = var.graphql_cert_private_key
  certificate_body = var.graphql_cert_certificate_body

  tags = merge(local.common_tags, {
    AppName     = "graphql",
    Environment = "${terraform.workspace}"
  })
} 
```
2.  Put the following in vars.tf file
```
variable "graphql_cert_private_key" {
  type        = string
  description = "private key for cert for graphql.example.com"
  default     = ""
}

variable "graphql_cert_certificate_body" {
  type        = string
  description = "The email addresses which will receive environment notifications (comma-separated)"
  default     = ""
}
```
3.  docker run -v <local-path>:/path checkmarx/kics:latest scan -p "/path" -o "/path" --verbose

### Specifications

-   Version: checkmarx/kics:latest
-   Platform: Ubuntu 22.04
-   Subsystem:

**Comment by cxMiguelSilva** [comment] 2022-09-26 10:25
Hi @arighosh2014, hope you are doing great!
Thank you so much for finding the bug in our terraform parser! The parser was not ready to get the certificate_body from tfvar, it was only expecting a hard string for the path.
The issue is being addressed in #5837

**Closed** 2022-09-27 09:30 UTC
Labels: bug, community
