### ISSUE TITLE
panic: interface conversion: interface {} is string, not yaml.Node

### ISSUE THREAD

**Issue by EsDmitrii** [Checkmarx/kics#6498] opened 2023-07-05 12:24 UTC
Hi!
Updated Kics from v1.7.1 to v1.7.2.
Started to get error `panic: interface conversion: interface {} is string, not yaml.Node`
All worked well before upgrade
Error log:
```
Scanning with Keeping Infrastructure as Code Secure v1.7.2
Preparing Scan Assets: Done                                                                                                                                                                  
panic: interface conversion: interface {} is string, not yaml.Node
goroutine 52 [running]:
github.com/Checkmarx/kics/pkg/resolver/file.(*Resolver).resolveYamlPath(0x40000fd1c8, {0x4000601500, 0x612, 0x700}, 0xa0000000025c58?, 0x4000aa5e00, {0x4000e14b40, 0x27}, 0x0, 0x2000?)
        /app/pkg/resolver/file/file.go:244 +0x7f4
github.com/Checkmarx/kics/pkg/resolver/file.(*Resolver).yamlWalk(0x40000fd1c8?, {0x4000601500, 0x612, 0x700}, 0x0?, 0x4000aa5e00, {0x4000e14b40, 0x27}, 0x0?, 0x40000fc5c8?)
        /app/pkg/resolver/file/file.go:154 +0x100
github.com/Checkmarx/kics/pkg/resolver/file.(*Resolver).yamlWalk(0x40000fd1c8?, {0x4000601500, 0x612, 0x700}, 0x0?, 0x4000aa5b80, {0x4000e14b40, 0x27}, 0x0?, 0x40015fe800?)
        /app/pkg/resolver/file/file.go:163 +0x280
github.com/Checkmarx/kics/pkg/resolver/file.(*Resolver).yamlWalk(0x2?, {0x4000601500, 0x612, 0x700}, 0x36?, 0x4000aa5540, {0x4000e14b40, 0x27}, 0x247d44?, 0x40000fca18?)
        /app/pkg/resolver/file/file.go:163 +0x280
github.com/Checkmarx/kics/pkg/resolver/file.(*Resolver).yamlWalk(0x40009c7cc0?, {0x4000601500, 0x612, 0x700}, 0x270b9c?, 0x40009c7e00, {0x4000e14b40, 0x27}, 0x204d060?, 0x40009c7d60?)
        /app/pkg/resolver/file/file.go:163 +0x280
github.com/Checkmarx/kics/pkg/resolver/file.(*Resolver).yamlWalk(0x3?, {0x4000601500, 0x612, 0x700}, 0x0?, 0x40009c7cc0, {0x4000e14b40, 0x27}, 0x25544?, 0x40000fcf68?)
        /app/pkg/resolver/file/file.go:163 +0x280
github.com/Checkmarx/kics/pkg/resolver/file.(*Resolver).yamlResolve(0x40000fd1c8, {0x4000601500, 0x612, 0x700}, {0x4000e14b40, 0x27}, 0x40000fd108?, 0x1d824?)
        /app/pkg/resolver/file/file.go:129 +0xec
github.com/Checkmarx/kics/pkg/resolver/file.(*Resolver).Resolve(0x40000fd1c8, {0x4000601500, 0x612, 0x700}, {0x4000e14b40, 0x27}, 0x40000fd1a8?, 0x23ba94?)
        /app/pkg/resolver/file/file.go:50 +0x200
github.com/Checkmarx/kics/pkg/parser/yaml.(*Parser).Resolve(0x4000126d50, {0x4000601500, 0x612, 0x700}, {0x4000e14b40, 0x27})
        /app/pkg/parser/yaml/parser.go:25 +0x108
github.com/Checkmarx/kics/pkg/parser.(*Parser).Parse(0x40017e8960, {0x4000e14b40, 0x27}, {0x4000601500, 0x612, 0x700})
        /app/pkg/parser/parser.go:124 +0xe4
github.com/Checkmarx/kics/pkg/kics.(*Service).sink(0x400087d340, {0x2765410, 0x4000136000}, {0x4000e14b40, 0x27}, {0x210a8c2, 0x7}, {0x2748400, 0x4000da66a8}, {0x4003560000, ...})
        /app/pkg/kics/sink.go:42 +0x134
github.com/Checkmarx/kics/pkg/kics.(*Service).PrepareSources.func1({0x2765410, 0x4000136000}, {0x4000e14b40, 0x27}, {0x2753608?, 0x4000da66a8})
        /app/pkg/kics/service.go:71 +0xa8
github.com/Checkmarx/kics/pkg/engine/provider.(*FileSystemSourceProvider).walkDir.func1({0x4000e14b40, 0x27}, {0x276cde0, 0x4000a749c0}, {0x0?, 0x0?})
        /app/pkg/engine/provider/filesystem.go:184 +0x3e0
path/filepath.walk({0x4000e14b40, 0x27}, {0x276cde0, 0x4000a749c0}, 0x40000fde08)
        /usr/local/go/src/path/filepath/path.go:480 +0xc8
path/filepath.walk({0x40005af500, 0x1b}, {0x276cde0, 0x4002c48840}, 0x40000fde08)
        /usr/local/go/src/path/filepath/path.go:504 +0x1d4
path/filepath.walk({0x400095bc10, 0xa}, {0x276cde0, 0x4002e5c000}, 0x40000fde08)
        /usr/local/go/src/path/filepath/path.go:504 +0x1d4
path/filepath.walk({0x400095a1f0, 0x6}, {0x276cde0, 0x400321cd80}, 0x40000fde08)
        /usr/local/go/src/path/filepath/path.go:504 +0x1d4
path/filepath.Walk({0x400095a1f0, 0x6}, 0x4001e24e08)
        /usr/local/go/src/path/filepath/path.go:571 +0x6c
github.com/Checkmarx/kics/pkg/engine/provider.(*FileSystemSourceProvider).walkDir(0x400095a1f0?, {0x2765410?, 0x4000136000?}, {0x400095a1f0?, 0x10000?}, 0x1, 0xffff6d391d28?, 0xffff947265b8?, 0x20?)
        /app/pkg/engine/provider/filesystem.go:146 +0x74
github.com/Checkmarx/kics/pkg/engine/provider.(*FileSystemSourceProvider).GetSources(0x40021192c0, {0x2765410, 0x4000136000}, 0xd40004?, 0x4003185980, 0x4000f918ed?)
        /app/pkg/engine/provider/filesystem.go:135 +0x170
github.com/Checkmarx/kics/pkg/kics.(*Service).PrepareSources(0x400087d340, {0x2765410, 0x4000136000}, {0x210a8c2, 0x7}, 0x0?, 0x0?)
        /app/pkg/kics/service.go:67 +0x1c0
created by github.com/Checkmarx/kics/pkg/scanner.PrepareAndScan
        /app/pkg/scanner/scanner.go:24 +0xb4
```

**Comment by gabriel-cx** [comment] 2023-07-05 13:24
Hi @EsDmitrii ,

Kindly check if this situation also happen when you use the latest KICS version, [v1.7.3](https://github.com/Checkmarx/kics/releases/tag/v1.7.3).
Let us know if the latest version fix your mentioned issue.

**Comment by EsDmitrii** [comment] 2023-07-05 13:25
Hi @gabriel-cx 
Forgot to mention that I have the same issue with latest version

**Comment by gabriel-cx** [comment] 2023-07-05 13:30
Thank you for your fast reply!

To better understand what can be the root cause, it is possible for you to send us the project/code sample that your are scanning when you get this panic issue?

If you available to share with us your code, so we can analyze it from our side, kindly send it to our email: kics@checkmarx.com.

**Comment by EsDmitrii** [comment] 2023-07-05 13:58
ahh unfortunately it's private source code.. a lot of sensitive data..
for example, I  opened an issue before, here it is https://github.com/Checkmarx/kics/issues/6458
There are couple examples of code with masked data
At this time I don't know which file causes the issue, there are about 400 yaml manifests that kics checks

**Comment by EsDmitrii** [comment] 2023-07-05 14:17
soo
I don't know what is the root cause
this option doesn't work:
`docker run -t -v /path/to/repo/root/dir:/path checkmarx/kics:latest scan -p /path/ -o "/path/" --config=/path/.kics-config.yaml -q /app/bin/assets/queries/common/passwords_and_secrets`

and this worked well:
`docker run -t -v /path/to/repo/root/dir:/path checkmarx/kics:v1.7.3 scan -p /path/yaml_dir/ -o "/path/" --config=/path/.kics-config.yaml -q /app/bin/assets/queries/common/passwords_and_secrets`

.kics-config.yaml is:
```
exclude-paths:
  - apps/
  - argocd/
  - env/
  - source/
exclude-queries:
  - baee238e-1921-4801-9c3f-79ae1d7b2cbc
```

**Comment by EsDmitrii** [comment] 2023-07-05 14:19
I suppose we can close the issue 
nothing bad with kics:)

**Comment by EsDmitrii** [comment] 2023-07-05 14:25
I have the last one question!
Kics checks a lot of files in our repo. Now there are about 400 files, and there will be more
Do you have some options  to run scans in multi-threaded mode?
Now it takes about 2.30 min in GitLab. Runner use about 2CPU and 1Gi RAM when Kics running.

**Comment by EsDmitrii** [comment] 2023-07-05 14:53
1. `-p /path/` is root dir of git repo. There are readme. codeowners, gitignore, etc.. No IAC files.
<img width="183" alt="Screenshot 2023-07-05 at 17 52 30" src="https://github.com/Checkmarx/kics/assets/124890665/98e5262c-b005-4b3f-b920-ad504507c910">

2. `-p /path/yaml_dir/` is dir with yamls to check (`tpl` on the screenshot).

**Comment by gabriel-cx** [comment] 2023-07-05 14:55
> I have the last one question! Kics checks a lot of files in our repo. Now there are about 400 files, and there will be more Do you have some options to run scans in multi-threaded mode? Now it takes about 2.30 min in GitLab. Runner use about 2CPU and 1Gi RAM when Kics running.
> 
> ```
> Scanning with Keeping Infrastructure as Code Secure v1.7.3
> Files scanned: 320
> Parsed files: 320
> Queries loaded: 0
> Queries failed to execute: 0
> Scan duration: 2m21.567751331s
> ```
> 
> I experimented locally with managing docker resources:
> 
> 2cpu\2ram <img alt="Screenshot 2023-07-05 at 17 45 54" width="962" src="https://user-images.githubusercontent.com/124890665/251188530-6585b953-f9b7-4151-a91b-5eff636b0124.png">
> 
> 8cpu\8ram <img alt="Screenshot 2023-07-05 at 17 44 08" width="968" src="https://user-images.githubusercontent.com/124890665/251188693-9f47c26d-138a-46ff-b747-e8524cf54252.png">
> 
> 10cpu\8ram <img alt="Screenshot 2023-07-05 at 17 45 14" width="965" src="https://user-images.githubusercontent.com/124890665/251188843-8813f559-06da-49b6-8a92-fca9d502d6f7.png">
> 
> In all situations Kics use about 90-95% of allocated CPU.. What if we can run checks in multi-threaded mode?

Currently, KICS runs [Concurrent Scans](https://docs.kics.io/latest/architecture/#concurrent_scans).
Internally we are analyzing possible ways to make scans faster but keeping the quality of results.

Does this information clarifies your doubts?

**Comment by EsDmitrii** [comment] 2023-07-05 14:56
> > I have the last one question! Kics checks a lot of files in our repo. Now there are about 400 files, and there will be more Do you have some options to run scans in multi-threaded mode? Now it takes about 2.30 min in GitLab. Runner use about 2CPU and 1Gi RAM when Kics running.
> > ```
> > Scanning with Keeping Infrastructure as Code Secure v1.7.3
> > Files scanned: 320
> > Parsed files: 320
> > Queries loaded: 0
> > Queries failed to execute: 0
> > Scan duration: 2m21.567751331s
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I experimented locally with managing docker resources:
> > 2cpu\2ram <img alt="Screenshot 2023-07-05 at 17 45 54" width="962" src="https://user-images.githubusercontent.com/124890665/251188530-6585b953-f9b7-4151-a91b-5eff636b0124.png">
> > 8cpu\8ram <img alt="Screenshot 2023-07-05 at 17 44 08" width="968" src="https://user-images.githubusercontent.com/124890665/251188693-9f47c26d-138a-46ff-b747-e8524cf54252.png">
> > 10cpu\8ram <img alt="Screenshot 2023-07-05 at 17 45 14" width="965" src="https://user-images.githubusercontent.com/124890665/251188843-8813f559-06da-49b6-8a92-fca9d502d6f7.png">
> > In all situations Kics use about 90-95% of allocated CPU.. What if we can run checks in multi-threaded mode?
> 
> Currently, KICS runs [Concurrent Scans](https://docs.kics.io/latest/architecture/#concurrent_scans). Internally we are analyzing possible ways to make scans faster but keeping the quality of results.
> 
> Does this information clarifies your doubts?

Thank you for your reply!
Yep, you answered my question:)

**Comment by gabriel-cx** [comment] 2023-07-05 15:08
> 1. `-p /path/` is root dir of git repo. There are readme, codeowners, gitignore, etc.. No IAC files.
> 
> <img alt="Screenshot 2023-07-05 at 17 52 30" width="183" src="https://user-images.githubusercontent.com/124890665/251190513-98e5262c-b005-4b3f-b920-ad504507c910.png">
> 2. `-p /path/yaml_dir/` is dir with yamls to check (_tpl_ on the screenshot).

Since there are no IaC files in that folder, that was the reason of the panic issued by KICS.
We will have a look, however, into that situation. But looks like KICS is working as expected when you give the path to the IaC files. Kindly close the issue if you do not have any more questions. 👍 

Feel free to open a new issue every time you need support from our side. Or send us an email to the address I sent you previously.

**Closed** 2023-07-05 15:14 UTC
Labels: bug, community

**Comment by EsDmitrii** [comment] 2023-07-05 15:15
The main funny thing that all worked well in 1.7.1:)
I thought that kics checked all directories and subdirectories)

**Comment by gabriel-cx** [comment] 2023-07-05 15:20
Yeah, that's the reason why we need to check it, probably something is not working as we expected! 
Thank you for your feedback on this!

**Comment by EsDmitrii** [comment] 2023-07-05 15:21
Any time!
Thank you for your assistance!
I appreciate this:)

**Comment by gabriel-cx** [comment] 2023-07-12 14:01
Hi @EsDmitrii ,

Just to let you know, we have a possible [fix ](https://github.com/Checkmarx/kics/pull/6511)for the problem you mentioned! We are testing it.
Have a great week.

**Comment by EsDmitrii** [comment] 2023-07-12 14:03
@gabriel-cx Hi!
woo, cool!
