### ISSUE TITLE
Update invalid_format query for OpenAPI

### ISSUE THREAD

**Issue by janlaan** [Checkmarx/kics#5747] opened 2022-08-31 14:15 UTC
### Platform
OpenAPI-General

### Description
This query: https://github.com/Checkmarx/kics/blob/master/assets/queries/openAPI/general/invalid_format
lists a number of valid formats for a string type field. However, the [OpenAPI documentation says](https://swagger.io/docs/specification/data-models/data-types/#format) string format is an open value, and can contain anything, not just the list in the query.

I believe this check should be removed for strings as it does not violate the OpenAPI specification and causes false positives.

**Comment by cxMiguelSilva** [comment] 2022-09-23 11:40
Hi @janlaan, hope you are doing great!
I'm glad to inform you that the issue is already being addressed in the PR #5831
Thank you for the input 😀!

**Closed** 2022-09-23 11:39 UTC
Labels: query, community
