### ISSUE TITLE
The "-q" flag doesn't work in folders containing dots (in folder name)

### ISSUE THREAD

**Issue by cxlucas** [Checkmarx/kics#3799] opened 2021-07-01 13:50 UTC
This bug has the same behavior as found in: https://github.com/Checkmarx/kics/issues/3769

### Expected Behavior

When running a scan with `-q folder-name` kics should find the queries within this folder.

### Actual Behavior

When running a kics scan with `-q folder.name`, kics doesn't find the folder and performs an empty scan.

### Steps to Reproduce the Problem

1.  You should have a valid file to perform a successful scan.
2. Open terminal.
3. Go to kics folder.
4. Run: `kics scan -p sample.tf -o path/output -q path/queries.files`

Kics will perform a scan with no queries (empty result).

### Specifications

-   Version: n/a
-   Platform: n/a
-   Subsystem: n/a

**Comment by felipe-avelar** [comment] 2021-07-02 11:22
@cxlucas Regarding the `-p` flag, we couldn't reproduce the error.
Regarding `-q` flag the problem is KICS queries must follow a fixed directory structure including assets/queries and assets/libraries, so it is not a bug.

Since the bug is not reproducible, I'm closing this issue

**Closed by felipe-avelar** 2021-07-02 11:22 UTC
Labels: bug
